import { ref } from "vue";

const legals = ref({
  "terms-of-use": {
    title: "Terms of Use",
    subtitle: "Last updated: September 3, 2023",
    content:
      'Welcome to Yarden\'s Portfolio Website (the "Website"). By accessing or using this Website, you agree to comply with and be bound by the following terms and conditions (the "Terms of Use"). Please read these Terms of Use carefully before using the Website.\n\n1. Acceptance of Terms\n\nBy accessing or using the Website, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use. If you do not agree to these Terms of Use, please do not use the Website.\n\n2. Intellectual Property\n\nAll content on this Website, including but not limited to text, images, graphics, videos, and logos, is the property of Yarden Yosef and is protected by copyright, trademark, and other intellectual property laws. You may not reproduce, modify, distribute, or otherwise use any content from this Website without the express written permission of Yarden Yosef.\n\n3. Use of Website\n\nYou agree to use the Website only for lawful purposes and in a manner that does not violate any applicable laws or regulations. You may not:\n\n- Use the Website to engage in any illegal or harmful activities.\n- Attempt to gain unauthorized access to any part of the Website or its related systems.\n- Transmit any content that is harmful, offensive, or violates the rights of others.\n\n4. Disclaimer\n\nThe content provided on this Website is for informational purposes only. Yarden Yosef makes no representations or warranties of any kind, express or implied, regarding the accuracy, completeness, or suitability of the content. You use the Website at your own risk.\n\n5. Links to Third-Party Websites\n\nThis Website may contain links to third-party websites. These links are provided for your convenience, and Yarden Yosef does not endorse or control the content of these websites. We are not responsible for the content or privacy practices of third-party websites.\n\n6. Changes to Terms\n\nYarden Yosef reserves the right to modify these Terms of Use at any time. Any changes will be effective immediately upon posting on the Website. Your continued use of the Website after any such changes will constitute your acceptance of the revised Terms of Use.\n\n7. Termination\n\nYarden Yosef reserves the right to terminate or suspend your access to the Website at any time, without notice, for any reason, including if you violate these Terms of Use.\n\n8. Contact Information\n\nIf you have any questions or concerns about these Terms of Use, please contact us at Yardenjobs@gmail.com.\n\n9. Governing Law\n\nThese Terms of Use are governed by and construed in accordance with the laws of Israel, without regard to its conflict of law principles.\n\nBy using this Website, you agree to submit to the exclusive jurisdiction of the courts located within Israel for the resolution of any disputes arising out of or related to these Terms of Use.',
  },

  "privacy-policy": {
    title: "Privacy Policy",
    subtitle: "Last updated: September 3, 2023",
    content:
      "Welcome to Yarden's Portfolio Website (the \"Website\"). This Privacy Policy explains how Yarden Yosef collects, uses, and protects your personal information when you use the Website.\n\n1. Information We Collect\n\nWe may collect personal information when you voluntarily provide it to us, such as when you fill out a contact form or subscribe to our newsletter. The types of personal information we may collect include your name, email address, and any other information you choose to provide.\n\n2. How We Use Your Information\n\nWe may use your personal information for various purposes, including to respond to your inquiries, send you updates or newsletters, and improve our Website's content and functionality.\n\n3. Cookies and Tracking Technologies\n\nWe may use cookies and similar tracking technologies to collect information about your browsing activities on our Website. You can adjust your browser settings to refuse cookies or to be notified when cookies are being sent.\n\n4. Third-Party Links\n\nOur Website may contain links to third-party websites. We do not control the privacy practices of these websites and are not responsible for their content or privacy policies. We encourage you to review the privacy policies of these third-party websites.\n\n5. Security\n\nWe take reasonable measures to protect your personal information from unauthorized access or disclosure. However, no online transmission or storage of data is entirely secure, and we cannot guarantee the security of your information.\n\n6. Changes to this Privacy Policy\n\nWe may update this Privacy Policy from time to time. Any changes will be posted on this page, and the date of the latest revision will be indicated at the top of the Privacy Policy.\n\n7. Contact Us\n\nIf you have any questions or concerns about this Privacy Policy or how we handle your personal information, please contact us at Yardenjobs@gmail.com.\n\nBy using this Website, you consent to the terms of this Privacy Policy.",
  },

  accessibility: {
    title: "Accessibility",
    subtitle: "Last updated: September 3, 2023",
    content:
      "At Yarden's Portfolio Website, we are committed to ensuring that our website is accessible to all users, including those with disabilities. We strive to provide an inclusive and user-friendly experience for everyone.\n\nAccessibility Features\n\n- We have designed our website with accessibility in mind, following best practices and standards to make it usable for people with various disabilities.\n\nFeedback and Suggestions\n\nWe value your feedback and welcome suggestions for improving the accessibility of our website. If you encounter any accessibility barriers or have suggestions for improvement, please contact us at Yardenjobs@gmail.com.\n\nOngoing Efforts\n\nWe are continuously working to improve the accessibility of our website and regularly review our content and design to ensure compliance with accessibility guidelines and standards.\n\nAccessibility Tools\n\nWe recommend using modern web browsers and assistive technologies to enhance your browsing experience. Popular web browsers often include built-in accessibility features, and there are various assistive technologies available to assist users with disabilities.\n\nContact Us\n\nIf you have any questions or concerns about the accessibility of our website or need assistance with any aspect of it, please contact us at Yardenjobs@gmail.com. We are dedicated to addressing and resolving any accessibility issues promptly.\n\nBy using this Website, you acknowledge our commitment to accessibility and agree to our efforts to provide an inclusive online environment for all users.",
  },
});

export default legals;
